### ISSUE TITLE
Validate W3C

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/zapto#15]
@sabas, try to validate the `.html` and tell me what you think.

**Comment by sabas** [comment]
rel="modal" is necessary for the plugin I think, so it's to be ignored...

`<input id='payment' type='hidden' placeholder='Clique aqui para adicionar' />`
 could be text? It should be tested if it works then.

`<button class='col12' id='collect-data-done'><h4>Gravar</h4></button>`
 try changing it to
`<h4><button class='col12' id='collect-data-done'>Gravar</button></h4>`

`<label for='payment'>` on the next line you need to add also name="payment" I think
`<input id='payment' name='payment' type='hidden' placeholder='Clique aqui para adicionar' />`

**Comment by alexandre-mbm** [comment]
Issues list:
1. modal
2. placeholder
3. h4
4. payment

My feedback:
1. See [HTML5 link type extensions](http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions) 
2. ~~`type="hidden"`~~
3. :+1: 
4. ~~`type="hidden"`~~

See the commit b602d1d0a8d9633217f8cadca8c7bbb156179652.

Thank you.
