### ISSUE TITLE
Mudança de endereço e possivelmente de nome

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/zapto#19]
Atualmente:
- [osmbra<b>z</b>il.zapto.org](http://osmbrazil.zapto.org/)
- [osmbra<b>s</b>il.zapto.org](http://osmbrasil.zapto.org/)

Mas a organização possui:
- [openstreetmap.com.br](http://www.openstreetmap.com.br/)

Sugiro:
- <b>no</b>.openstreetmap.com.br

Os subdomínios de zapto.org são gratuitos e precisam ser reconfirmados por e-mail a cada mês.

**Comment by alexandre-mbm** [comment]
Por enquanto, o nome do projeto foi mudado de `osm-zapto` para apenas `zapto`. Antes havia o acesso ~~[alexandre-mbm.github.io/osm-zapto](http://alexandre-mbm.github.io/osm-zapto)~~, agora haverá [osmbrasil.github.io/zapto](http://osmbrasil.github.io/zapto). Eu espero.

~~O teste que acabo de fazer só passa para [osmbrasil.github.io/osm-zapto](http://osmbrasil.github.io/osm-zapto). Isso deve ser algum processamento pendente, a geração do gh-pages, por exemplo.~~ → resolvido na _issue_ #21

**Comment by alexandre-mbm** [comment]
[openstreetmap.com.br/zapto](http://www.openstreetmap.com.br/zapto/) → [www.openstreetmap.com.br/zapto](http://www.openstreetmap.com.br/zapto/)

Parece estar satisfatório.

Ou o administrador do DNS configuraria, por exemplo:

```
no.openstreetmap.com.br ← CNAME osmbrasil.github.io
```

Ou seria melhor o seguinte?

```
zapto.openstreetmap.com.br ← CNAME osmbrasil.github.io
```

Ou fica sem subdomínio, como já está?

**Comment by vgeorge** [comment]
Já resolvido com o .com.br, não?

**Comment by alexandre-mbm** [comment]
@vgeorge, sim se vocês usarão a estratégia `openstreetmap.com.br/APP` invés da estratégia `APP.openstreetmap.com.br`. É o que vocês decidirem. Eu sugiro a segunda.
