### ISSUE TITLE
Adicione um campo para descrição

### ISSUE THREAD

**Issue by IgorEliezer** [OSMBrasil/zapto#27]
Repostando o meu comentário na comunidade do OSM/BR:

Antes o Zapto parecia um formulário de INSS, cheio de campos, nem parecia que era para o público geral usar. Agora ficou mais limpo, só que ficou limpo de mais: só nome, endereço, telefone e site.

Acho que poderia colocar um campo `"Mais alguma informação relevante? (opcional - até 280 caracteres)"` dando liberdade para o usuário escrever o que achar necessário. Normalmente o pessoal que adiciona o seu próprio comércio no OSM, adiciona dados como horário de atendimento, se tem estacionamento, wi-fi, se serve comida x y z, se o lugar é agradável etc.

Por isso que é interessante ter um campo livre para descrever, ao invés de ter um campo para cada coisa, assuntando o leigo que não quer ser mapeador, que é justamente o público que o zapto se propõe alcançar. Aí fica a critério do mapeador interpretar e julgar o que é mapeável.

**Comment by eduardoaddad** [comment]
Adicionado campo
