### ISSUE TITLE
Correspondência para Key:wheelchair

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/zapto#4]
Ref. 1: http://forum.openstreetmap.org/viewtopic.php?pid=416637#p416637
Ref. 2: http://wiki.openstreetmap.org/wiki/Key:wheelchair
Ref. 3: http://forum.openstreetmap.org/viewtopic.php?pid=416831#p416831 (translations)
Ref. 4: http://wiki.openstreetmap.org/wiki/Pt-br:Key:wheelchair (translations)

**Comment by alexandre-mbm** [comment]
@jgpacker, o que você achou da tradução [Pt-br:Key:wheelchair](http://wiki.openstreetmap.org/wiki/Pt-br:Key:wheelchair)? 

Por favor, acompanhe a _issue_ — sabas/suosm#11 — no repositório italiano.

**Comment by alexandre-mbm** [comment]
@jgpacker, fiz. Testa aí! Vê se atende, se era isso.

**Comment by sabas** [comment]
@alexandre-mbm some people say that designated value means a different  thing (purpose built)

**Comment by alexandre-mbm** [comment]
@sabas, this thing is almost implicit. Some people just imply.
