### ISSUE TITLE
Vales-refeição e cartões de benefício

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/zapto#8]
- [ ] [sodexo](https://sodexosaldocartao.com.br)
- [ ] [alelo](http://www.alelo.com.br/)

Quero adicionar todos de uma só vez. 

Retirar estas traduções "inválidas":
- [x] Ticket Restaurante
- [x] Ticket Alimentação

Ref.: http://forum.openstreetmap.org/viewtopic.php?pid=416797#p416797

**Pesquisando cartões de benefício**
1. Tenho pesquisado "[cartões de benefício](cartões de benefício)" no Google mas estou com dificuldades para determinar os resultam que importam.
2. Talvez eu deva adicionar todos os [cartões de benefício divulgados por userede.com.br](http://www.userede.com.br/pt-BR/conhecaredecard/Paginas/cartoesbeneficio.aspx).
3. Quais seriam os [cartões de benefício do Grupo Pão de Açucar](http://www.grupopaodeacucar.com.br/cartoesdebeneficios/)?
4. O [cortacontas](https://www.cortacontas.com.br/cartao-de-credito) oferece uma pesquisa de cartões variados, incluindo os de benefício. O site retorna mais de 300 cartões de benefício. Seria lícito fazer um _import_ dos nomes? Ou talvez devamos escolher entre os cartões encontrados...
5. Outros resultados que a pesquisa Google retornou-me separadamente:
- [Cartões Unik](http://www.unik.com.br/)
- [Sapore Benefícios](http://www.saporebeneficios.com.br/)
- [Banrisul Cartões](http://www.banrisulservicos.com.br/bdr/link/bdrw00hw_produtos_detalhe.asp?secao_id=66)
- [Sorocred](http://www.sorocred.com.br/novo_site/pagina.asp?mnu=2&id=24)
- [Cartão SESIMAX](http://www.sesimax.com.br/cartoes_sesi_max.asp?idArea=3413&idSubMenu=3428)

**Comment by alexandre-mbm** [comment]
~~Vamos gerenciar esses dados em uma página do [wiki do OpenStreetMap](http://wiki.openstreetmap.org)?~~

Decidi por uma [planilha no Google Docs](https://docs.google.com/spreadsheets/d/1pCBpaB8yST_G7lbiL4y4yiGgB73L2uZRbkOaHhYSsR4/edit?pli=1#gid=0). Qualquer um pode submeter **comentários**. Quem desejar, solicite-me **direitos de edição**.

---

Os seguintes provedores de informações (já referidos acima, na _issue_) já constam na planilha:
- [x] Sodexo
- [x] Alelo
- [x] Unik
- [x] Sapore
- [x] Banrisul
- [x] Sorocred
- [x] SESIMAX
- [x] Grupo Pão de Açucar

Da fonte [userede.com.br](http://www.userede.com.br/pt-BR/conhecaredecard/Paginas/cartoesbeneficio.aspx):
- [x] [coopercred](http://www.coopercred.com/portal/produtos.php)
- [x] [greencard](https://www.grupogreencard.com.br/servicos.php)
- [x] [nutricash](http://www.nutricash.com.br/produtos.aspx)
- [x] [planvale](http://www.planvale.com.br/produtos.php)
- [x] [ticket](http://www.ticket.com.br/portal/portalcorporativo/home/home.htm)
- [x] [valecard](https://www.valecard.com.br/portal/web/guest/produtos)
- [x] [cabal](http://www.cabal.com.br/pt/)
- [x] [verocheque](http://www.verocheque.com.br/)
- [x] [vb](https://www.vb.com.br/)
- [x] [bnbclube](http://www.bnbclube.com.br/index.php?option=com_content&view=category&id=13&Itemid=32)

Da fonte [cortacontas.com.br](https://www.cortacontas.com.br/cartao-de-credito):
- [ ] ..

Como filtrar dessa última fonte as informações que nos interessam?

Para alguns grupos de "cartões", deveríamos apenas considerar as **bandeiras**?

![bandeiras-de-cartao](https://cloud.githubusercontent.com/assets/957501/2847474/b4443982-d0ae-11e3-8d50-53161b36f8d6.png)

**Comment by alexandre-mbm** [comment]
Em caso afirmativo, vamos gerenciar bandeiras de cartão aqui:
- [x] Elo
- [x] Smiles
- [x] Hipercard
- [x] Aura
- [x] ~~Diners~~ Diners Club
- [x] American Express
- [x] MasterCard
- [x] Visa

**Comment by alexandre-mbm** [comment]
Ref.: http://wiki.openstreetmap.org/wiki/Key:payment
Eu tinha esquecido de olhar...

**Comment by alexandre-mbm** [comment]
@jgpacker, dê uma olhada na [planilha](https://docs.google.com/spreadsheets/d/1pCBpaB8yST_G7lbiL4y4yiGgB73L2uZRbkOaHhYSsR4/edit?pli=1#gid=0). Vou deixar como está; ou seja, [cortacontas.com.br](https://www.cortacontas.com.br/cartao-de-credito) de fora, apenas como fonte de consulta para verificações de futuras solicitações de inclusão de cartões no [ozm-zapto](/alexandre-mbm/ozm-zapto). Então agora temos apenas que decidir sobre o que está na planilha, como aproveitar.

Quero simplesmente usar o formato `[agência] ‒ [cartão]` na ordem alfabética, assim:

```
- Coopercred ‒ Cooper Crad Vale Alimentação
- ...
```

Concorda?

**Comment by jgpacker** [comment]
Eu acho que colocar só a marca de forma genérica já basta porque (1) na maioria dos casos, o tipo do cartão pode ser inferido pelo contexto (por exemplo, se um objeto tem `payment:sodexo=yes` e é um posto de combustível, então seria o _Sodexo Combustível Pass_, já em um restaurante seria o _Sodexo Refeição Pass_ e (2) adicionar todos os cartões colocaria opções demais para os usuários escolherem.

**Comment by alexandre-mbm** [comment]
Concordo. Obrigado.

Por isso é melhor eu perguntar. Eu nem sabia ainda que o mapeamento se faz com uma tag como `payment:sodexo=yes`. Não tenho experiência de mapeamento e não tenho tempo para estudar cada detalhe.

Se eu encontrar algum caso confuso, quando for fazer, volto a comentar aqui.
